name: 機能の要望
description: 新しい機能や改善の提案はこちら
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
    validations: {required: true}
  - type: textarea
    id: proposal
    attributes:
      label: 望ましい動作
    validations: {required: true}
